[project]
name = "expensy"
version = "0.1.0-alpha.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1,<9",
    "colorama>=0.4.6",
]
